# Generated by Django 3.2.19 on 2025-12-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20251112_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='shop_schema.shop_cartitem',
        ),
        migrations.AlterModelTable(
            name='category',
            table='shop_schema.shop_category',
        ),
        migrations.AlterModelTable(
            name='order',
            table='shop_schema.shop_order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_schema.shop_product',
        ),
        migrations.AlterModelTable(
            name='review',
            table='shop_schema.shop_review',
        ),
        migrations.AlterModelTable(
            name='user',
            table='shop_schema.shop_user',
        ),
    ]
